- name: siem_agent_apt
  hosts: siem_agent_hosts
  become: true
  become_user: root
  tasks:
    - name: Ensure curl installed
      ansible.builtin.apt:
        name: "curl"
        state: present
    
    - name: Ensure gpg installed
      ansible.builtin.apt:
        name: "gpg"
        state: present
    
    # - name: Remove old apt key
    #   ansible.builtin.shell: "rm -f /usr/share/keyrings/wazuh.gpg"

    - name: Fetch SIEM GPG key
      ansible.builtin.shell: "curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | gpg --no-default-keyring --keyring gnupg-ring:/usr/share/keyrings/wazuh.gpg --import && chmod 644 /usr/share/keyrings/wazuh.gpg"
        creates: /usr/share/keyrings/wazuh.gpg

    - name: Set up SIEM apt repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/wazuh.gpg] https://packages.wazuh.com/4.x/apt/ stable main"
        state: present

    - name: Install SIEM agent
      ansible.builtin.apt:
        name: "wazuh-agent"
        state: latest
        update_cache: yes
      environment:
        WAZUH_MANAGER: "koma.cosi.clarkson.edu"
    
    - name: Run SIEM agent
      ansible.builtin.systemd_service:
        state: started
        daemon_reload: true
        name: wazuh-agent
